apiVersion: v2
name: doplane
description: A Helm chart for the Pulumi Do operator
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/dirien/doplane
sources:
  - https://github.com/dirien/doplane
maintainers:
  - name: dirien
    email: engin.diri@ediri.de
keywords:
  - pulumi
  - kubernetes
  - operator
  - platform-engineering
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: manager
      image: ghcr.io/dirien/doplane:0.1.0
    - name: runner
      image: ghcr.io/dirien/doplane-runner:0.1.0
