/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"encoding/json"
	"fmt"
	"strings"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/utils/ptr"

	dov1alpha1 "github.com/dirien/doplane/api/v1alpha1"
	"github.com/dirien/doplane/internal/pulumido"
)

// typedGroup is the API group of all generated typed CRDs (managed
// resources and composite APIs). One fixed group keeps manager RBAC
// enumerable.
const typedGroup = "typed.do.pulumi.com"

// typedVersion is the served/storage version of generated CRDs.
const typedVersion = "v1alpha1"

// kindFromToken derives the CRD kind from a resource token:
// "aws:s3/bucketV2:BucketV2" → "BucketV2".
func kindFromToken(token string) string {
	if i := strings.LastIndex(token, ":"); i >= 0 {
		return token[i+1:]
	}
	return token
}

// pluralize lowercases a kind into a naive plural resource name.
func pluralize(kind string) string {
	lower := strings.ToLower(kind)
	switch {
	case strings.HasSuffix(lower, "s"), strings.HasSuffix(lower, "x"), strings.HasSuffix(lower, "ch"):
		return lower + "es"
	case strings.HasSuffix(lower, "y") && len(lower) > 1 && !strings.ContainsRune("aeiou", rune(lower[len(lower)-2])):
		return lower[:len(lower)-1] + "ies"
	default:
		return lower + "s"
	}
}

// propsToJSONSchema converts a Pulumi property schema into the structural
// OpenAPI subset CRDs accept. Unresolvable shapes ($ref, oneOf, unknown
// types) degrade to a value with unknown fields preserved — validation is
// still enforced end to end by the controller's registry-schema check.
func propsToJSONSchema(p pulumido.PropertySchema) apiextensionsv1.JSONSchemaProps {
	switch p.Type {
	case "string", "boolean", "integer", "number":
		return apiextensionsv1.JSONSchemaProps{Type: p.Type}
	case "array":
		items := apiextensionsv1.JSONSchemaProps{XPreserveUnknownFields: ptr.To(true)}
		if p.Items != nil {
			items = propsToJSONSchema(*p.Items)
		}
		return apiextensionsv1.JSONSchemaProps{
			Type:  "array",
			Items: &apiextensionsv1.JSONSchemaPropsOrArray{Schema: &items},
		}
	case "object":
		obj := apiextensionsv1.JSONSchemaProps{Type: "object"}
		if p.AdditionalProperties != nil {
			ap := propsToJSONSchema(*p.AdditionalProperties)
			obj.AdditionalProperties = &apiextensionsv1.JSONSchemaPropsOrBool{Schema: &ap}
		} else {
			obj.XPreserveUnknownFields = ptr.To(true)
		}
		return obj
	default:
		// $ref, oneOf and friends: accept anything at this node.
		return apiextensionsv1.JSONSchemaProps{XPreserveUnknownFields: ptr.To(true)}
	}
}

// typedResourceCRD builds the CRD for one provider resource token: spec
// carries providerRef/forProvider/deletionPolicy, forProvider validated
// from the provider's input schema.
func typedResourceCRD(token string, schema *pulumido.PackageSchema) (*apiextensionsv1.CustomResourceDefinition, error) {
	res, ok := schema.Resources[token]
	if !ok {
		return nil, fmt.Errorf("resource type %q not found in schema of %s@%s", token, schema.Name, schema.Version)
	}
	kind := kindFromToken(token)
	plural := pluralize(kind)

	forProvider := apiextensionsv1.JSONSchemaProps{
		Type:       "object",
		Properties: map[string]apiextensionsv1.JSONSchemaProps{},
		Required:   append([]string(nil), res.RequiredInputs...),
	}
	for name, prop := range res.InputProperties {
		forProvider.Properties[name] = propsToJSONSchema(prop)
	}

	spec := apiextensionsv1.JSONSchemaProps{
		Type:     "object",
		Required: []string{"forProvider"},
		Properties: map[string]apiextensionsv1.JSONSchemaProps{
			"providerRef": {
				Type:     "object",
				Required: []string{"name"},
				Properties: map[string]apiextensionsv1.JSONSchemaProps{
					"name": {Type: "string", MinLength: ptr.To(int64(1))},
					"kind": {Type: "string", Enum: []apiextensionsv1.JSON{
						{Raw: []byte(`"DoProvider"`)}, {Raw: []byte(`"DoProviderConfig"`)},
					}},
				},
			},
			"forProvider":    forProvider,
			"deletionPolicy": {Type: "string", Enum: []apiextensionsv1.JSON{{Raw: []byte(`"Delete"`)}, {Raw: []byte(`"Orphan"`)}}},
		},
	}
	source := "resource"
	if res.IsComponent {
		source = "component"
	}
	return typedCRD(kind, plural, spec,
		fmt.Sprintf("Generated by doplane from Pulumi %s %s (%s@%s).", source, token, schema.Name, schema.Version)), nil
}

// typedCompositeCRD builds the CRD for a definition's platform API: the
// typed object's spec is the composite's parameters.
func typedCompositeCRD(def string, api *dov1alpha1.CompositeAPI) (*apiextensionsv1.CustomResourceDefinition, error) {
	spec := apiextensionsv1.JSONSchemaProps{Type: "object", XPreserveUnknownFields: ptr.To(true)}
	if api.ParametersSchema != nil && len(api.ParametersSchema.Raw) > 0 {
		var parsed apiextensionsv1.JSONSchemaProps
		if err := json.Unmarshal(api.ParametersSchema.Raw, &parsed); err != nil {
			return nil, fmt.Errorf("spec.api.parametersSchema is not a JSONSchemaProps document: %w", err)
		}
		spec = parsed
	}
	plural := api.Plural
	if plural == "" {
		plural = pluralize(api.Kind)
	}
	return typedCRD(api.Kind, plural, spec,
		fmt.Sprintf("Generated by doplane from DoCompositeDefinition %q.", def)), nil
}

// typedCRD assembles the shared CRD shell: namespaced, status subresource,
// printer columns mirroring the underlying object's conditions.
//
// Deliberately NO OwnerReference to the generating DoProvider/
// DoCompositeDefinition. Both are cluster-scoped, so a cross-object owner ref
// is technically valid and would let the garbage collector clean up the CRD on
// source deletion — but deleting a served CRD deletes every CR of that kind,
// each of which owns a mirror DoResource whose finalizer tears down a real
// cloud resource. Cascade GC would therefore turn an accidental
// `kubectl delete doprovider …` into mass destruction of managed
// infrastructure. Fail-safe wins here: an orphaned CRD (and its idle
// translation controller) is a bounded, benign leak; deleting live cloud
// resources is not. If lifecycle cleanup is wanted, add a finalizer on the
// source that BLOCKS its deletion while typed CRs exist and only then deletes
// the CRD — never a plain owner-ref cascade.
func typedCRD(kind, plural string, spec apiextensionsv1.JSONSchemaProps, description string) *apiextensionsv1.CustomResourceDefinition {
	return &apiextensionsv1.CustomResourceDefinition{
		ObjectMeta: metav1.ObjectMeta{
			Name:   plural + "." + typedGroup,
			Labels: map[string]string{labelManagedByKey: "doplane"},
		},
		Spec: apiextensionsv1.CustomResourceDefinitionSpec{
			Group: typedGroup,
			Scope: apiextensionsv1.NamespaceScoped,
			Names: apiextensionsv1.CustomResourceDefinitionNames{
				Kind:     kind,
				ListKind: kind + "List",
				Plural:   plural,
				Singular: strings.ToLower(kind),
			},
			Versions: []apiextensionsv1.CustomResourceDefinitionVersion{{
				Name:    typedVersion,
				Served:  true,
				Storage: true,
				Subresources: &apiextensionsv1.CustomResourceSubresources{
					Status: &apiextensionsv1.CustomResourceSubresourceStatus{},
				},
				AdditionalPrinterColumns: []apiextensionsv1.CustomResourceColumnDefinition{
					{Name: "READY", Type: "string", JSONPath: `.status.conditions[?(@.type=='Ready')].status`},
					{Name: "SYNCED", Type: "string", JSONPath: `.status.conditions[?(@.type=='Synced')].status`},
					{Name: "REASON", Type: "string", JSONPath: `.status.conditions[?(@.type=='Synced')].reason`},
					{Name: "AGE", Type: "date", JSONPath: `.metadata.creationTimestamp`},
				},
				Schema: &apiextensionsv1.CustomResourceValidation{
					OpenAPIV3Schema: &apiextensionsv1.JSONSchemaProps{
						Type:        "object",
						Description: description,
						Properties: map[string]apiextensionsv1.JSONSchemaProps{
							"spec":   spec,
							"status": {Type: "object", XPreserveUnknownFields: ptr.To(true)},
						},
					},
				},
			}},
		},
	}
}
