apiVersion: v2
name: pulumi-do-operator
description: A Helm chart for the Pulumi Do operator
type: application
version: 0.1.0
appVersion: 0.0.1
home: https://github.com/dirien/pulumi-do-operator
sources:
  - https://github.com/dirien/pulumi-do-operator
maintainers:
  - name: dirien
    email: engin.diri@ediri.de
keywords:
  - pulumi
  - kubernetes
  - operator
  - platform-engineering
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: manager
      image: controller:latest
    - name: runner
      image: pulumi-do-runner:dev
