{{- if and .Values.metrics.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "doplane.metricsMonitorName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "doplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    control-plane: controller-manager
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - path: {{ .Values.metrics.serviceMonitor.path }}
      port: https
      scheme: {{ .Values.metrics.serviceMonitor.scheme }}
      {{- with .Values.metrics.serviceMonitor.bearerTokenFile }}
      bearerTokenFile: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      tlsConfig:
        {{- if .Values.metrics.serviceMonitor.tlsConfig }}
        {{- toYaml .Values.metrics.serviceMonitor.tlsConfig | nindent 8 }}
        {{- else }}
        insecureSkipVerify: {{ .Values.metrics.serviceMonitor.insecureSkipVerify }}
        {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "doplane.managerSelectorLabels" . | nindent 6 }}
{{- end }}
